// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package types

type Atom struct {
	UID int64  `form:"uid,required"`
	Sid string `form:"sid,required"`
}

type CommenceRequest struct {
	Atom
	PackageID int64 `json:"package_id"`
}

type CommenceResponse struct {
}

type Package struct {
	ID                  int64  `json:"id"`
	Title               string `json:"title"`
	Type                int64  `json:"type"`
	WordCount           int64  `json:"word_count"`
	Learners            int64  `json:"learners"`
	RememberedWordCount int64  `json:"remembered_word_count"`
	CategoryCode        int64  `json:"category_code"`
}
