// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	packageMemorizingFieldNames          = builder.RawFieldNames(&PackageMemorizing{})
	packageMemorizingRows                = strings.Join(packageMemorizingFieldNames, ",")
	packageMemorizingRowsExpectAutoSet   = strings.Join(stringx.Remove(packageMemorizingFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	packageMemorizingRowsWithPlaceHolder = strings.Join(stringx.Remove(packageMemorizingFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	packageMemorizingModel interface {
		Insert(ctx context.Context, data *PackageMemorizing) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*PackageMemorizing, error)
		FindOneByUidPackageId(ctx context.Context, uid uint64, packageId uint64) (*PackageMemorizing, error)
		Update(ctx context.Context, data *PackageMemorizing) error
		Delete(ctx context.Context, id int64) error
	}

	defaultPackageMemorizingModel struct {
		conn  sqlx.SqlConn
		table string
	}

	PackageMemorizing struct {
		Id          int64     `db:"id"`
		Uid         uint64    `db:"uid"`          //  用户 ID
		PackageType uint64    `db:"package_type"` // 词包类型
		PackageId   uint64    `db:"package_id"`   // 词包ID
		CreateTime  time.Time `db:"create_time"`  // 创建时间
		UpdateTime  time.Time `db:"update_time"`  // 更新时间
	}
)

func newPackageMemorizingModel(conn sqlx.SqlConn) *defaultPackageMemorizingModel {
	return &defaultPackageMemorizingModel{
		conn:  conn,
		table: "`package_memorizing`",
	}
}

func (m *defaultPackageMemorizingModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultPackageMemorizingModel) FindOne(ctx context.Context, id int64) (*PackageMemorizing, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", packageMemorizingRows, m.table)
	var resp PackageMemorizing
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPackageMemorizingModel) FindOneByUidPackageId(ctx context.Context, uid uint64, packageId uint64) (*PackageMemorizing, error) {
	var resp PackageMemorizing
	query := fmt.Sprintf("select %s from %s where `uid` = ? and `package_id` = ? limit 1", packageMemorizingRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, uid, packageId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPackageMemorizingModel) Insert(ctx context.Context, data *PackageMemorizing) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, packageMemorizingRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Uid, data.PackageType, data.PackageId)
	return ret, err
}

func (m *defaultPackageMemorizingModel) Update(ctx context.Context, newData *PackageMemorizing) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, packageMemorizingRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Uid, newData.PackageType, newData.PackageId, newData.Id)
	return err
}

func (m *defaultPackageMemorizingModel) tableName() string {
	return m.table
}
